- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common tools
  apt:
    name:
      - curl
      - git
      - nano
      - cowsay
    state: present