services:
  haproxy:
    image: haproxy:3.2
    container_name: haproxy
    volumes:
      - /home/ubuntu/docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    expose:
      - "8080"
    networks: [edge]
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks: [edge]
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${TUNNEL_TOKEN}"]
    depends_on:
      - haproxy

networks:
  edge: {}