server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mktxp-syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: "syslog"
          __path__: /var/log/syslog-ng/*.log
    pipeline_stages:
      - match:
          selector: '{job="syslog"}'
          stages:
            - regex:
                source: filename
                expression: "/var/log/syslog-ng/(?P<routerboard>.+).log"
            - labels:
                routerboard:
      # optional timestamp parsing
      - regex:
          expression: '^(?P<ts>\\w{3}\\s+\\d{1,2}\\s\\d{2}:\\d{2}:\\d{2})'
      - timestamp:
          source: ts
          format: 'Jan _2 15:04:05'
          location: Europe/Brussels